### ISSUE TITLE
Exception running CLI & Roslyn with Unity set to 4.6

### ISSUE THREAD

**Issue by DianeOfTheMoon** [sschmid/Entitas-CSharp#494]
Hey there.

When trying to switch to .NET 4.6 in my project, running Entitas.exe gen gives me the following error on windows:

```
System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Entitas.Roslyn.ProjectParser.GetTypes()
   at Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider.GetData()
   at Entitas.CodeGeneration.CodeGenerator.CodeGenerator.generate(String messagePrefix, ICodeGeneratorDataProvider[] dataProviders, ICodeGenerator[] codeGenerators, ICodeGenFilePostProcessor[] postProcessors)
   at Entitas.CodeGeneration.CodeGenerator.CodeGenerator.DryRun()
   at Entitas.CodeGeneration.CodeGenerator.CLI.Doctor.run()
   at Entitas.CodeGeneration.CodeGenerator.CLI.Program.Main(String[] args)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
```

Any ideas on what might be going on?

**Comment by DianeOfTheMoon** [comment]
It looks like I was missing the developer pack.
