### ISSUE TITLE
Jenny auto-import throwing KeyNotFoundException with no properties file

### ISSUE THREAD

**Issue by DianeOfTheMoon** [sschmid/Entitas-CSharp#527]
I started with a project where I deleted Entitas.properties, User.properties, <user>.properties and Preferences.properties, and on running jenny.exe auto-import, this is what I get:

```
Jenny.exe auto-import -v

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DesperateDevs.Serialization.Properties.get_Item(String key)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGeneratorConfig.get_searchPaths()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.AutoImport.autoImport()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.AutoImport.run()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.AbstractPreferencesCommand.Run(String[] args)
   at DesperateDevs.CLI.CLIProgram.runCommand(String[] args)
```

**Comment by DianeOfTheMoon** [comment]
This is when trying to run Unity with 4.6 experimental

**Comment by sschmid** [comment]
Just to be sure, try running `jenny fix` as described  in  #519 . I f the problem still exists afterwards, please let me know

**Comment by DianeOfTheMoon** [comment]
It does, but the generated file seems to have jenny hang on parsing the Assembly-CSharp.csproj file.

```
D:\strategyrpg>CodeGenerator\Jenny gen -v
AppDomain load: Entitas.CodeGeneration.Plugins
  ? Loading: Entitas.CodeGeneration.Plugins
    √ Resolved: CodeGenerator\Plugins\Entitas\Entitas.CodeGeneration.Plugins.dll
AppDomain load: Entitas.VisualDebugging.CodeGeneration.Plugins
  ? Loading: Entitas.VisualDebugging.CodeGeneration.Plugins
    √ Resolved: CodeGenerator\Plugins\Entitas\Entitas.VisualDebugging.CodeGeneration.Plugins.dll
AppDomain load: DesperateDevs.CodeGeneration.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Plugins
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\DesperateDevs.CodeGeneration.Plugins.dll
AppDomain load: Entitas.Roslyn.CodeGeneration.Plugins
  ? Loading: Entitas.Roslyn.CodeGeneration.Plugins
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Entitas.Roslyn.CodeGeneration.Plugins.dll
AppDomain load: DesperateDevs.CodeGeneration.Unity.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Unity.Plugins
    √ Resolved: CodeGenerator\Plugins\Jenny\DesperateDevs.CodeGeneration.Unity.Plugins.dll
Pre Processing: Fix Target Framework Profile (4%)
Creating model: Context (8%)
Creating model: Component (Roslyn) (12%)
Opening Assembly-CSharp.csproj
  ? Loading: System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.Collections.Immutable.dll
  ? Loading: SQLitePCLRaw.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1488e028ca7ab535
    x Could not resolve: SQLitePCLRaw.core.dll
  ? Loading: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.dll
  ? Loading: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Framework.dll
  ? Loading: Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.dll
  ? Loading: Microsoft.Build, Version=14.1.0.0, Culture=neutral
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.dll
  ? Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  ? Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  ? Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  ? Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  ? Loading: System.Reflection.Metadata, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.Reflection.Metadata.dll
  ? Loading: Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Utilities.Core.dll
  ? Loading: Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Framework.dll
  ? Loading: Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.dll
  ? Loading: Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.CodeAnalysis.CSharp.dll
  ? Loading: Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    √ Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.CodeAnalysis.dll
Opened Assembly-CSharp
Parsing Assembly-CSharp
```
...and then it just sits there.

**Comment by sschmid** [comment]
Ok, that's new. It doesn't continue? Is the project in a working state? How long did you wait for the parsing to finish? (sorry, I have to ask all this, I never heard of this issue)

**Comment by DianeOfTheMoon** [comment]
I waited a couple of minutes before closing the console.

**Comment by DianeOfTheMoon** [comment]
It seems to have something to do with deleting the output directory.

**Comment by sschmid** [comment]
Is this still an issue for you?

**Comment by ArkTarusov** [comment]
@sschmid hi. We have a similar problem.
We use CI Teamcity, import settings and .csproj, when trying to generate or doctor it hangs on parsing .csproj


Entitas 1.13.0
Unity 2018.3.6f
TeamCity Professional 2018.2.3 (build 61544)

**Comment by ArkTarusov** [comment]
The problem turned out to be in the very .csproj.
It is necessary on each computer, after each update of the project, to regenerate a new .csproj file.
Simply sending it from the developer’s computer does not work, since not all files are generated. For example, in the current project, 108 files are generated on the developer’s computer, only 93 files are generated on the build computer.
This can be solved by opening c# project in unity editor, but this requires a monodevelop or a visual studio, which are not on the assembly computer, and if there is, then everything needs to be done exactly by hand. For us, this is not an acceptable option.
