### ISSUE TITLE
Unable to generate on new machine

### ISSUE THREAD

**Issue by DianeOfTheMoon** [sschmid/Entitas-CSharp#549]
Hey,

I switched to a laptop for travel, and attempting to generate creates the following error:

```
>CodeGenerator\Jenny.exe gen -v
AppDomain load: Entitas.CodeGeneration.Plugins
  ? Loading: Entitas.CodeGeneration.Plugins
    √ Resolved: CodeGenerator/Plugins\Entitas\Entitas.CodeGeneration.Plugins.dll
AppDomain load: Entitas.VisualDebugging.CodeGeneration.Plugins
  ? Loading: Entitas.VisualDebugging.CodeGeneration.Plugins
    √ Resolved: CodeGenerator/Plugins\Entitas\Entitas.VisualDebugging.CodeGeneration.Plugins.dll
AppDomain load: DesperateDevs.CodeGeneration.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Plugins
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\DesperateDevs.CodeGeneration.Plugins.dll
AppDomain load: Entitas.Roslyn.CodeGeneration.Plugins
  ? Loading: Entitas.Roslyn.CodeGeneration.Plugins
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Entitas.Roslyn.CodeGeneration.Plugins.dll
AppDomain load: DesperateDevs.CodeGeneration.Unity.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Unity.Plugins
    √ Resolved: CodeGenerator/Plugins\Jenny\DesperateDevs.CodeGeneration.Unity.Plugins.dll
Pre Processing: Fix Target Framework Profile (4%)
Creating model: Context (8%)
Creating model: Component (Roslyn) (12%)
Opening Assembly-CSharp.csproj
  ? Loading: System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\System.Collections.Immutable.dll
  ? Loading: SQLitePCLRaw.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1488e028ca7ab535
    x Could not resolve: SQLitePCLRaw.core.dll
  ? Loading: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.dll
  ? Loading: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Framework.dll
  ? Loading: Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.dll
  ? Loading: Microsoft.Build, Version=14.1.0.0, Culture=neutral
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.dll
  ? Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  ? Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  ? Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  ? Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  ? Loading: Microsoft.Build.Tasks.Core.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.resources.dll
  ? Loading: Microsoft.Build.Tasks.Core.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.resources.dll
  ? Loading: Microsoft.Build.Tasks.Core.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.resources.dll
  ? Loading: Microsoft.Build.Tasks.Core.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.resources.dll
  ? Loading: System.Reflection.Metadata, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\System.Reflection.Metadata.dll
  ? Loading: Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Utilities.Core.dll
  ? Loading: Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Framework.dll
  ? Loading: Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.dll
  ? Loading: Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.CodeAnalysis.CSharp.dll
  ? Loading: Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    √ Resolved: CodeGenerator/Plugins\Entitas.Roslyn\Microsoft.CodeAnalysis.dll
Opened Assembly-CSharp
Parsing Assembly-CSharp
  ? Loading: Microsoft.CodeAnalysis.resources, Version=2.4.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
    x Could not resolve: Microsoft.CodeAnalysis.resources.dll
  ? Loading: Microsoft.CodeAnalysis.resources, Version=2.4.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
    x Could not resolve: Microsoft.CodeAnalysis.resources.dll
  ? Loading: Microsoft.CodeAnalysis.resources, Version=2.4.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
    x Could not resolve: Microsoft.CodeAnalysis.resources.dll
  ? Loading: Microsoft.CodeAnalysis.resources, Version=2.4.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
    x Could not resolve: Microsoft.CodeAnalysis.resources.dll
System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Entitas.Roslyn.ProjectParser.GetTypes()
   at Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider.GetData()
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.generate(String messagePrefix, IPreProcessor[] preProcessors, IDataProvider[] dataProviders, ICodeGenerator[] codeGenerators, IPostProcessor[] postProcessors)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.Generate()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.AbstractPreferencesCommand.Run(String[] args)
   at DesperateDevs.CLI.CLIProgram.runCommand(String[] args)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

```

Any ideas on how to correct?

**Comment by DianeOfTheMoon** [comment]
Looks like there was an issue with the 4.6 targeting framework.  Once I updated, generation was working.
