### ISSUE TITLE
Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by yanjingzhaisun** [sschmid/Entitas-CSharp#595]
Hi,

I was trying to generate code from terminal in windows using powershell. Then the terminal gives me erro information about "Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified." This is the information from Jenny doctor -v:

Loading assemblies from D:\UnityProject\entitas-test\Jenny
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Analytics.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Analytics.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.CLI.Utils.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.CLI.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.CodeGeneration.CodeGenerator.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.CodeGeneration.CodeGenerator.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.CodeGeneration.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.CodeGeneration.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Logging.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Logging.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Logging.Formatters.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Logging.Formatters.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Networking.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Networking.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Serialization.CLI.Utils.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Serialization.CLI.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Serialization.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Serialization.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Utils.dll
  ? Loading: D:\UnityProject\entitas-test\Jenny\DesperateDevs.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: D:\UnityProject\entitas-test\Jenny\Jenny.exe
  ? Loading: D:\UnityProject\entitas-test\Jenny\Jenny.exe
Jenny.SearchPaths = Assets/Entitas/Editor/Plugins/DesperateDevs, \
                    Assets/Entitas/Editor/Plugins/Entitas, \
                    Assets\Entitas\Editor\Plugins\DesperateDevs, \
                    Assets\Entitas\Editor\Plugins\Entitas, \
                    Jenny\Plugins\Entitas.Roslyn

Jenny.Plugins = DesperateDevs.CodeGeneration.Plugins, \
                DesperateDevs.CodeGeneration.Unity.Plugins, \
                Entitas.CodeGeneration.Plugins, \
                Entitas.VisualDebugging.CodeGeneration.Plugins, \
                Entitas.Roslyn.CodeGeneration.Plugins

Jenny.PreProcessors = DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor
Jenny.DataProviders = Entitas.CodeGeneration.Plugins.ComponentDataProvider, \
                      Entitas.CodeGeneration.Plugins.ContextDataProvider, \
                      Entitas.CodeGeneration.Plugins.EntityIndexDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider

Jenny.CodeGenerators = Entitas.CodeGeneration.Plugins.ComponentContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentsLookupGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextAttributeGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextsGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityIndexGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator

Jenny.PostProcessors = DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor

Jenny.Server.Port = 3333
Jenny.Client.Host = localhost
DesperateDevs.CodeGeneration.Plugins.ProjectPath = entitas-test.csproj
Entitas.CodeGeneration.Plugins.Assemblies = Library/ScriptAssemblies/Assembly-CSharp.dll
Entitas.CodeGeneration.Plugins.Contexts = Game, \
                                          Input, \
                                          Build

Entitas.CodeGeneration.Plugins.IgnoreNamespaces = false
DesperateDevs.CodeGeneration.Plugins.TargetDirectory = Assets/Sources
Jenny.Ignore.Keys =
Preferences.Entitas = Entitas.Unity.Editor.EntitasPreferencesDrawer, \
                      DesperateDevs.CodeGeneration.CodeGenerator.Unity.Editor.CodeGeneratorPreferencesDrawer, \
                      Entitas.VisualDebugging.Unity.Editor.VisualDebuggingPreferencesDrawer

Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold = 5
Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath = Assets/Editor/DefaultInstanceCreator
Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath = Assets/Editor/TypeDrawer

Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Plugins
    ? Resolved: Assets/Entitas/Editor/Plugins/DesperateDevs\DesperateDevs.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Unity.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Unity.Plugins
    ? Resolved: Assets/Entitas/Editor/Plugins/DesperateDevs\DesperateDevs.CodeGeneration.Unity.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.CodeGeneration.Plugins
  ? Loading: Entitas.CodeGeneration.Plugins
    ? Resolved: Assets/Entitas/Editor/Plugins/Entitas\Entitas.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.VisualDebugging.CodeGeneration.Plugins
  ? Loading: Entitas.VisualDebugging.CodeGeneration.Plugins
    ? Resolved: Assets/Entitas/Editor/Plugins/Entitas\Entitas.VisualDebugging.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.Roslyn.CodeGeneration.Plugins
  ? Loading: Entitas.Roslyn.CodeGeneration.Plugins
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Entitas.Roslyn.CodeGeneration.Plugins.dll
???  Unused key: Preferences.Entitas
???  Unused key: Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold
???  Unused key: Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath
???  Unused key: Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
??  Potential collision detected: ComponentDataProvider -> Entitas.CodeGeneration.Plugins.ComponentDataProvider
??  Potential collision detected: ComponentDataProvider -> Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider
??  Potential collision detected: EntityIndexDataProvider -> Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
??  Potential collision detected: EntityIndexDataProvider -> Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider
  ? Loading Dependency: System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\System.Collections.Immutable.dll
  ? Loading Dependency: System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\System.IO.Compression.dll
?????  Symptoms: Entitas.CodeGeneration.Plugins.ComponentDataProvider loads and reflects Library/ScriptAssemblies/Assembly-CSharp.dll and therefore doesn't support server mode!
??  Treatment: Don't use the code generator in server mode with Entitas.CodeGeneration.Plugins.ComponentDataProvider
?????  Symptoms: Entitas.CodeGeneration.Plugins.EntityIndexDataProvider loads and reflects Library/ScriptAssemblies/Assembly-CSharp.dll and therefore doesn't support server mode!
??  Treatment: Don't use the code generator in server mode with Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
Dry Run
Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Plugins
    ? Resolved: Assets/Entitas/Editor/Plugins/DesperateDevs\DesperateDevs.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Unity.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Unity.Plugins
    ? Resolved: Assets/Entitas/Editor/Plugins/DesperateDevs\DesperateDevs.CodeGeneration.Unity.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.CodeGeneration.Plugins
  ? Loading: Entitas.CodeGeneration.Plugins
    ? Resolved: Assets/Entitas/Editor/Plugins/Entitas\Entitas.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.VisualDebugging.CodeGeneration.Plugins
  ? Loading: Entitas.VisualDebugging.CodeGeneration.Plugins
    ? Resolved: Assets/Entitas/Editor/Plugins/Entitas\Entitas.VisualDebugging.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.Roslyn.CodeGeneration.Plugins
  ? Loading: Entitas.Roslyn.CodeGeneration.Plugins
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Entitas.Roslyn.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Library/ScriptAssemblies/Assembly-CSharp.dll
  ? Loading: Library/ScriptAssemblies/Assembly-CSharp.dll
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: Entitas.CodeGeneration.Attributes, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Entitas.CodeGeneration.Attributes.dll
  ? Loading Dependency: Entitas.VisualDebugging.Unity, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: Entitas.VisualDebugging.Unity, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: Entitas.VisualDebugging.Unity, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
  ? Loading Dependency: UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
System.IO.FileNotFoundException: Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at DesperateDevs.Utils.PublicMemberInfo..ctor(FieldInfo info)
   at DesperateDevs.Utils.PublicMemberInfoExtension.GetPublicMemberInfos(Type type)
   at Entitas.CodeGeneration.Plugins.MemberDataComponentDataProvider.Provide(Type type, ComponentData data)
   at Entitas.CodeGeneration.Plugins.ComponentDataProvider.createDataForComponent(Type type)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.generate(String messagePrefix, IPreProcessor[] preProcessors, IDataProvider[] dataProviders, ICodeGenerator[] codeGenerators, IPostProcessor[] postProcessors)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.DryRun()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.DoctorCommand.run()
   at DesperateDevs.Serialization.CLI.Utils.AbstractPreferencesCommand.Run(String[] args)
   at DesperateDevs.CLI.Utils.CLIProgram.runCommand(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by yanjingzhaisun** [comment]
Got it. Turn off internal ones and stick with Roslyn. Working now!
