### ISSUE TITLE
Windows code generation - client server issues

### ISSUE THREAD

**Issue by nbreum15** [sschmid/Entitas-CSharp#623]
Hi,

When I start the server and run the generate command on the client I get:
```
PS A:\GitHub\EntitasProject> .\CodeGenerator\Jenny.exe client gen -v
Client is connecting to ::1:3333...
System.NotSupportedException: This protocol version is not supported.
   at System.Net.Sockets.Socket.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)
   at DesperateDevs.Networking.TcpClientSocket.Connect(IPAddress ipAddress, Int32 port)
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.Client.run()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.AbstractPreferencesCommand.Run(String[] args)
   at DesperateDevs.CLI.CLIProgram.runCommand(String[] args)
```
Previous versions of entitas all worked fine for me. I think this happens with Entitas 1.0 and higher.

**Comment by sschmid** [comment]
Hm, network code hasn't been changed in recent versions. I guess it's an IPv6 issue.
Can you enter your actual local ip address instead of "localhost" and see if it works?

```
Jenny.Client.Host = localhost
```

**Comment by nbreum15** [comment]
Trying that I get:
```
.\CodeGenerator\Jenny.exe client gen -v
System.IndexOutOfRangeException: index was outside the bounds of the array.
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.Client.run()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.AbstractPreferencesCommand.Run(String[] args)
   at DesperateDevs.CLI.CLIProgram.runCommand(String[] args)
```

**Comment by sschmid** [comment]
Can I see the properties file, there might be sth setup not correctly

**Comment by nbreum15** [comment]
Entitas properties:
```
CodeGenerator.SearchPaths = CodeGenerator\Plugins, \
                            Assets\Entitas\Editor, \
                            CodeGenerator\Plugins\Entitas, \
                            CodeGenerator\Plugins\Entitas.Roslyn, \
                            CodeGenerator\Plugins\Jenny

CodeGenerator.Plugins = Entitas.CodeGeneration.Plugins, \
                        Entitas.VisualDebugging.CodeGeneration.Plugins, \
                        DesperateDevs.CodeGeneration.Plugins, \
                        Entitas.Roslyn.CodeGeneration.Plugins, \
                        DesperateDevs.CodeGeneration.Unity.Plugins

CodeGenerator.DataProviders = Entitas.CodeGeneration.Plugins.ContextDataProvider, \
                              Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider, \
                              Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider

CodeGenerator.CodeGenerators = Entitas.CodeGeneration.Plugins.ComponentContextGenerator, \
                               Entitas.CodeGeneration.Plugins.ComponentEntityGenerator, \
                               Entitas.CodeGeneration.Plugins.ComponentEntityInterfaceGenerator, \
                               Entitas.CodeGeneration.Plugins.ComponentGenerator, \
                               Entitas.CodeGeneration.Plugins.ComponentMatcherGenerator, \
                               Entitas.CodeGeneration.Plugins.ComponentsLookupGenerator, \
                               Entitas.CodeGeneration.Plugins.ContextAttributeGenerator, \
                               Entitas.CodeGeneration.Plugins.ContextGenerator, \
                               Entitas.CodeGeneration.Plugins.ContextMatcherGenerator, \
                               Entitas.CodeGeneration.Plugins.ContextsGenerator, \
                               Entitas.CodeGeneration.Plugins.EntityGenerator, \
                               Entitas.CodeGeneration.Plugins.EntityIndexGenerator, \
                               Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator, \
                               Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator

CodeGenerator.PostProcessors = DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor, \
                               DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor, \
                               DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor, \
                               DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor, \
                               DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor, \
                               DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor, \
                               DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor, \
                               DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor

CodeGenerator.Server.Port = 3333
CodeGenerator.Client.Host = 172.20.0.253
Entitas.CodeGeneration.Plugins.Contexts = Core, \
                                          Input, \
                                          Command

Entitas.CodeGeneration.Plugins.IgnoreNamespaces = true
DesperateDevs.CodeGeneration.Plugins.TargetDirectory = Assets\Sources
DesperateDevs.CodeGeneration.Plugins.ProjectPath = EntitasProject.csproj
CodeGenerator.CLI.Ignore.UnusedKeys = 
```

**Comment by nbreum15** [comment]
Is there a way to check which Entitas version you're running?

**Comment by StormRene** [comment]
Yes. You can call the cli without parameter and you'll see the version. In your case:
`PS A:\GitHub\EntitasProject> .\CodeGenerator\Jenny.exe`

**Comment by sschmid** [comment]
Since Jenny became its own project, it doesn't show the Entitas version anymore. Opening the Entitas Preferences in Unity shows the version in the title of the window.

Did the issue resolve? Have you tried `auto-import`?

**Comment by nbreum15** [comment]
I didn't realize that I was still on 0.46.1 (thanks new Asset Store for not letting me update). However, unfortunately the problem is still there in version 1.4.0. If it helps any, the generator worked fine on version 0.46.3.

Here is my properties after `auto-import` on version 1.4.0:
```
Preferences.Entitas = Entitas.Unity.Editor.EntitasPreferencesDrawer, \
                      DesperateDevs.CodeGeneration.CodeGenerator.Unity.Editor.CodeGeneratorPreferencesDrawer, \
                      Entitas.VisualDebugging.Unity.Editor.VisualDebuggingPreferencesDrawer

Jenny.SearchPaths = Assets\Entitas\Editor\Plugins\DesperateDevs, \
                    Assets\Entitas\Editor\Plugins\Entitas

Jenny.Plugins = DesperateDevs.CodeGeneration.Plugins, \
                DesperateDevs.CodeGeneration.Unity.Plugins, \
                Entitas.CodeGeneration.Plugins, \
                Entitas.VisualDebugging.CodeGeneration.Plugins

Jenny.PreProcessors = DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor
Jenny.DataProviders = Entitas.CodeGeneration.Plugins.ComponentDataProvider, \
                      Entitas.CodeGeneration.Plugins.ContextDataProvider, \
                      Entitas.CodeGeneration.Plugins.EntityIndexDataProvider

Jenny.CodeGenerators = Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentLookupGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextAttributeGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextsGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityIndexGenerator, \
                       Entitas.CodeGeneration.Plugins.EventEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenerComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenertInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemsGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator

Jenny.PostProcessors = DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor, \
                       DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor

Jenny.Server.Port = 3333
Jenny.Client.Host = localhost
Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold = 5
Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath = Assets\Editor\DefaultInstanceCreator
Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath = Assets\Editor\TypeDrawer
DesperateDevs.CodeGeneration.Plugins.ProjectPath = EntitasProject.csproj
Entitas.CodeGeneration.Plugins.Assemblies = Library/ScriptAssemblies/Assembly-CSharp.dll
Entitas.CodeGeneration.Plugins.Contexts = Core, \
                                          Input, \
                                          Command

Entitas.CodeGeneration.Plugins.IgnoreNamespaces = true
DesperateDevs.CodeGeneration.Plugins.TargetDirectory = Assets\Sources
```

If I start the server I get an error related to the port:
```
.\CodeGenerator\Jenny.exe server -v
System.Collections.Generic.KeyNotFoundException: the given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DesperateDevs.Serialization.Properties.get_Item(String key)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGeneratorConfig.get_port()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.Server.run()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.AbstractPreferencesCommand.Run(String[] args)
   at DesperateDevs.CLI.CLIProgram.runCommand(String[] args)
```

**Comment by StormRene** [comment]
You can try `jenny fix` and after that again `jenny auto-import`.

**Comment by nbreum15** [comment]
Think I was using the wrong Jenny.exe. My problem is now exactly the same as #628, so I am closing this one.
