### ISSUE TITLE
Race conditions in unit tests

### ISSUE THREAD

**Issue by ribbanya** [sschmid/Entitas-CSharp#872]
When using `Matcher`s in unit tests, a race condition will often occur that causes tests using a matcher to fail. Rerunning the tests repeatedly causes them to all eventually pass. Each rerun causes one or two more tests to pass.

```
System.ArgumentException
Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Entitas.Matcher`1.mergeIndices(Int32[] allOfIndices, Int32[] anyOfIndices, Int32[] noneOfIndices)
   at Entitas.Matcher`1.get_indices()
   at Entitas.Context`1.GetGroup(IMatcher`1 matcher)
   at Contexts.InitializeEntityIndices() in Path\To\My\UnityProject\Assets\Generated\Contexts.cs:line 76
```

**Comment by sschmid** [comment]
Are you executing your tests in parallel on different threads? Otherwise I don't understand why there should be race conditions

**Comment by ribbanya** [comment]
I believe that is what Rider does, yes.

**Comment by ribbanya** [comment]
I checked my settings. In theory, Rider should only be using one thread for unit testing. Not sure what's causing the race, if that's true.

**Comment by StormRene** [comment]
Hey ribbanya,
can you provide some code from a test that is have a race condition? Never had race condition problems with entitas and unit tests.

**Comment by sschmid** [comment]
Probably fixed by #919
